version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
  build:
    commands:
      - npm i
      - npm run build
      - (cd ./dist && zip -r Deploy.zip ./)
      - aws s3 mv ./dist/Deploy.zip s3://neo-ticket-${ENVIRONMENT_NAME}-release/resources/${CODEBUILD_BUILD_NUMBER}/Deploy.zip
      - aws cloudformation deploy
          --stack-name neo-ticket-${ENVIRONMENT_NAME}-resources
          --template-file infra/resources.yaml
          --s3-bucket neo-ticket-${ENVIRONMENT_NAME}-release
          --s3-prefix templates/outputs
          --parameter-overrides NameTag=${NAME_TAG} EnvName=${ENVIRONMENT_NAME} ObjectKeyPrefix=resources/${CODEBUILD_BUILD_NUMBER}
          --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM
      - cd ..
artifacts:
  files:
    - '**/*'
  base-directory: /